import { HeatPoint } from "@/types";

// PLATE_TO_AREA — Fretadão (1332 placas, 52 unidades)
export const PLATE_TO_AREA: Record<string, string> = {
  "ATB6B08": "G3 Transportadora",
  "ATH7259": "Ribeiro Tur",
  "AUA7671": "G3 Transportadora",
  "AVF5444": "G3 Transportadora",
  "AVN6I12": "G3 Transportadora",
  "AVX2018": "Ribeiro Tur",
  "AXP5A61": "G3 Transportadora",
  "AYN2044": "G3 Transportadora",
  "AYT1F58": "G3 Transportadora",
  "AYW7B34": "Piccolotur Taipas",
  "AZI2D57": "G3 Transportadora",
  "AZP6F84": "Amanhecer",
  "BAC3I68": "Karoline E Juliano",
  "BAK7E96": "Pantur",
  "BAK8G31": "RealceTur",
  "BAK8H90": "Amanhecer",
  "BAW2J69": "Karoline E Juliano",
  "BBR3A45": "Ribeiro Tur",
  "BBY3922": "Dinatur",
  "BCD9730": "G3 Transportadora",
  "BCK1D40": "Pantur",
  "BCT4A29": "Unitac Logistica e Tecnologia LTDA",
  "BEF6G77": "G3 Transportadora",
  "BEG0337": "G3 Transportadora",
  "BEG0377": "G3 Transportadora",
  "BEG3077": "G3 Transportadora",
  "BEG3G37": "G3 Transportadora",
  "BEG3H07": "G3 Transportadora",
  "BEG6G33": "G3 Transportadora",
  "BEG7330": "G3 Transportadora",
  "BEG7710": "G3 Transportadora",
  "BEG7720": "G3 Transportadora",
  "BEG7730": "G3 Transportadora",
  "BEG7740": "G3 Transportadora",
  "BEG7750": "G3 Transportadora",
  "BEG7760": "G3 Transportadora",
  "BEG7790": "G3 Transportadora",
  "BEG7797": "G3 Transportadora",
  "BEG7D03": "G3 Transportadora",
  "BEG7G37": "G3 Transportadora",
  "BEG7G66": "G3 Transportadora",
  "BEG7G75": "G3 Transportadora",
  "BEG7H80": "G3 Transportadora",
  "BFZ7467": "Rápido Campinas",
  "BFZ7505": "Rápido Campinas",
  "BFZ7516": "Rápido Campinas",
  "BFZ7569": "Rápido Campinas",
  "BFZ7574": "Rápido Campinas",
  "BFZ7760": "Piccolotur Guarulhos",
  "BFZ7958": "Branca de Neve",
  "BFZ8038": "Branca de Neve",
  "BFZ8377": "Rápido Campinas",
  "BFZ8475": "Branca de Neve",
  "BFZ8476": "Piccolotur Guarulhos",
  "BFZ8584": "Branca de Neve",
  "BFZ8592": "Branca de Neve",
  "BFZ8593": "Branca de Neve",
  "BFZ8601": "Branca de Neve",
  "BFZ8602": "Piccolotur Guarulhos",
  "BIQ6C12": "Piracicabana Breda (Santos)",
  "BNK5E05": "Piracicabana Breda (Santos)",
  "BRY1E81": "Transmimo Jundiai",
  "BSY2B39": "Micro Tur",
  "BSZ6G33": "Famatur",
  "BVK8I19": "Karoline E Juliano",
  "BWH5A87": "Transmimo Jundiai",
  "BWT9I85": "Transmimo Jundiai",
  "BWW6C17": "Viação Mimo São José",
  "BXD1930": "Transluz",
  "BYJ0H41": "Transmimo Jundiai",
  "BYJ8J85": "Fretadão - MATRIZ",
  "BYP2B41": "Piccolotur Guarulhos",
  "BYX7E85": "Qualitat",
  "BZA9F62": "Piracicabana Breda (Santos)",
  "BZB2G79": "Piccolotur Jundiai",
  "BZF3F74": "Fretadão - MATRIZ",
  "BZR5F41": "Amanhecer",
  "BZR6E06": "Tel Turismo",
  "CBZ8C78": "Rio Negro",
  "CDR0H95": "Tel Turismo",
  "CDR4B23": "Famatur",
  "CIY7B22": "Famatur",
  "CLU2033": "Venetur",
  "CNI1292": "Venetur",
  "CNI1506": "Venetur",
  "CNI1518": "Venetur",
  "CPN3J83": "Tel Turismo",
  "CSK2865": "Max Tour Atibaia",
  "CSK2H07": "Venetur",
  "CSK2H33": "Venetur",
  "CSK2H38": "Venetur",
  "CSR7111": "AS Service",
  "CUA0226": "Dinatur",
  "CUA0C24": "Dinatur",
  "CUA0C78": "Max Tour Bragança Extrema",
  "CUA0C80": "Max Tour Bragança Extrema",
  "CUB0C35": "Rápido Campinas",
  "CUB0C65": "Max Tour Atibaia",
  "CUG9B63": "Transmimo Jundiai",
  "CUH0E53": "Qualitat",
  "CUH6J20": "Piccolotur Taipas",
  "CUI1F04": "Qualitat",
  "CUI6D53": "Qualitat",
  "CUL9E07": "Viação Jacareí",
  "CUL9H29": "Piccolotur Jundiai",
  "CUN0H87": "Transmimo Jundiai",
  "CUQ0A75": "Fretadão - MATRIZ",
  "CUT2530": "Gold Turismo",
  "CUT2550": "Gold Turismo",
  "CUT3B60": "Gold Turismo",
  "CUT3D30": "Gold Turismo",
  "CUT5I10": "Gold Turismo",
  "CUT5I30": "Gold Turismo",
  "CUY0I40": "Sussantur",
  "CUY5I08": "Sussantur",
  "CUY7D10": "Sussantur",
  "CVN3664": "Rápido Campinas",
  "DAJ3E16": "ByBus",
  "DAR3J41": "Transmimo Jundiai",
  "DBA5C48": "Fretadão - MATRIZ",
  "DBC5B64": "Ribeiro Tur",
  "DBL8946": "Max Tour Atibaia",
  "DBS6140": "Micro Tur",
  "DCU2D93": "Max Tour Bragança Extrema",
  "DCU7C71": "Qualitat",
  "DED4577": "Branca de Neve",
  "DEI0H66": "Qualitat",
  "DEI0J66": "Viação Jacareí",
  "DEU8858": "Famatur",
  "DGY0A71": "Fretadão - MATRIZ",
  "DGY5A17": "Tel Turismo",
  "DIB6E81": "Transmimo Jundiai",
  "DIO8129": "Pantur",
  "DJC6I66": "Ribeiro Tur",
  "DLW5859": "Viação Lima E Silva Ltda",
  "DMS7F01": "Piracicabana Breda (Santos)",
  "DMZ0052": "Tel Turismo",
  "DPJ0E52": "Ribeiro Tur",
  "DRT2E21": "Tel Turismo",
  "DSB5B72": "ByBus",
  "DSQ4D05": "Tel Turismo",
  "DSR8F09": "Viação Jacareí",
  "DSV9D32": "Tel Turismo",
  "DSX4B11": "Transmimo Jundiai",
  "DTN1C99": "Transmimo Jundiai",
  "DUD1G09": "Transmimo Jundiai",
  "DWK4E82": "Transluz",
  "DZC9720": "Micro Tur",
  "DZM6266": "Fretadão - MATRIZ",
  "DZR4449": "Tel Turismo",
  "EBF5D62": "Transmimo Jundiai",
  "EBG7A81": "Tel Turismo",
  "EBV9B97": "Ribeiro Tur",
  "ECM6103": "Amanhecer",
  "ECM6104": "Amanhecer",
  "ECM6112": "Amanhecer",
  "ECM6116": "Amanhecer",
  "ECM6287": "Piccolotur Taipas",
  "ECM6412": "Piccolotur Taipas",
  "ECM6426": "Piccolotur Taipas",
  "ECM6E19": "Piccolotur Taipas",
  "ECM6E25": "Piccolotur Taipas",
  "ECM9A55": "Fretadão - MATRIZ",
  "ECT1D93": "Piccolotur Guarulhos",
  "ECU6B79": "Tel Turismo",
  "EDI5C64": "Tel Turismo",
  "EED8A24": "Qualitat",
  "EEU1A79": "Rio Negro",
  "EFO3E82": "Micro Tur",
  "EFO3I42": "Micro Tur",
  "EFO3I97": "Micro Tur",
  "EFO3J02": "Micro Tur",
  "EFO3J08": "Micro Tur",
  "EFU2E84": "Venetur",
  "EFU2E85": "Venetur",
  "EFV3930": "Fretadão - MATRIZ",
  "EFW3250": "Ribeiro Tur",
  "EFW3760": "Piccolotur Taipas",
  "EFW3H54": "Piccolotur Taipas",
  "EFW3I02": "Piccolotur Taipas",
  "EFW3I13": "Piccolotur Guarulhos",
  "EFW3I56": "Piccolotur Jundiai",
  "EFW3I95": "Piccolotur Taipas",
  "EFW4790": "Pavão Turismo",
  "EFW4B21": "Piccolotur Guarulhos",
  "EFW6230": "Ribeiro Tur",
  "EGB1D95": "Piccolotur Jundiai",
  "EGJ2C14": "ByBus",
  "EGJ4A88": "Aguia Turismo",
  "EGJ6361": "Piccolotur Taipas",
  "EGJ6D62": "Piccolotur Taipas",
  "EGX8I86": "Transmimo Jundiai",
  "EHH0B49": "Viação Lima E Silva Ltda",
  "EJQ5044": "Tel Turismo",
  "EJV1J22": "Venetur",
  "EJV8369": "Pavão Turismo",
  "EJV8D71": "Max Tour Bragança Extrema",
  "EJW1982": "Transluz",
  "EJW4193": "Dinatur",
  "EJW7307": "Transluz",
  "EJW7F60": "Transluz",
  "EJW7G59": "Transluz",
  "EJW7G63": "Transluz",
  "EJW7J12": "Transluz",
  "EJY9057": "Rápido Campinas",
  "EJY9204": "Rápido Campinas",
  "EJY9228": "Rápido Campinas",
  "EJY9287": "Rápido Campinas",
  "EJY9315": "Rápido Campinas",
  "EJY9322": "Rápido Campinas",
  "EJZ8673": "Venetur",
  "EKH0E29": "Universal Tour",
  "EKH2347": "Dinatur",
  "EKH2490": "Dinatur",
  "EKH2491": "Dinatur",
  "EKH2493": "Dinatur",
  "EKH2494": "Dinatur",
  "EKH7I08": "Max Tour Bragança Extrema",
  "EKH8G90": "Tamboré",
  "EKK3B87": "Famatur",
  "EKU8763": "Amanhecer",
  "ELE0G73": "Tel Turismo",
  "ELE5E22": "Piccolotur Jundiai",
  "ELM7I59": "Max Tour Bragança Extrema",
  "ELQ1H87": "Piccolotur Taipas",
  "ELT8E51": "ByBus",
  "ELV2477": "Tel Turismo",
  "ELW6788": "Transguerra",
  "EMU5780": "AS Service",
  "EMU5790": "AS Service",
  "EMU9H92": "Piccolotur Taipas",
  "EMU9H93": "Piccolotur Taipas",
  "END5J58": "Tamboré",
  "ENE7363": "Amanhecer",
  "ENN2D62": "Piccolotur Taipas",
  "ENN2I66": "Qualitat",
  "EOB4G86": "Transmimo Jundiai",
  "EOC3J98": "Viação Lima E Silva Ltda",
  "EOF4836": "Piccolotur Guarulhos",
  "EOF4H91": "Piccolotur Guarulhos",
  "EOF6428": "Micro Tur",
  "EOF6891": "Micro Tur",
  "EOF6892": "Micro Tur",
  "EOF6893": "Micro Tur",
  "EOF6953": "Micro Tur",
  "EOF6I97": "Max Tour Bragança Extrema",
  "EOF7063": "Micro Tur",
  "EOF7064": "Micro Tur",
  "EOF7702": "Micro Tur",
  "EOO2024": "Branca de Neve",
  "EOO2857": "AS Service",
  "EPA1898": "Exclusiva Turismo Caieiras e Jundiai",
  "EPU2I00": "Viação Lima E Silva Ltda",
  "EPU4908": "Max Tour Atibaia",
  "EPU5549": "Venetur",
  "EPU6941": "Venetur",
  "EQD8H51": "Piracicabana Breda (Santos)",
  "EQJ3E80": "Transmimo Jundiai",
  "EQU4B37": "Viação Mimo São José",
  "EQU5504": "Max Tour Atibaia",
  "EQU5734": "Max Tour Atibaia",
  "EQU5F21": "Max Tour Bragança Extrema",
  "EQU5F24": "Max Tour Bragança Extrema",
  "EQW6370": "Piccolotur Jundiai",
  "ERN2E85": "Rápido Campinas",
  "ERT9J11": "Fretadão - MATRIZ",
  "ESU5444": "Piccolotur Guarulhos",
  "ESU8C85": "Max Tour Bragança Extrema",
  "ESU8C86": "Max Tour Bragança Extrema",
  "ESU8C88": "Max Tour Bragança Extrema",
  "ESU8C90": "Max Tour Bragança Extrema",
  "ESU8C91": "Max Tour Bragança Extrema",
  "ESU8C94": "Max Tour Bragança Extrema",
  "ETA9I51": "Tamboré",
  "ETC5E82": "Tel Turismo",
  "ETU1056": "Transmimo Jundiai",
  "ETU1098": "Rápido Campinas",
  "ETU1099": "Rápido Campinas",
  "ETU1100": "Rápido Campinas",
  "ETU1146": "Transmimo Jundiai",
  "ETU1147": "Transmimo Jundiai",
  "ETU1406": "Rápido Campinas",
  "ETU1493": "Transmimo Jundiai",
  "ETU1604": "Bortolotto Fretamento",
  "ETU1941": "Transmimo Jundiai",
  "ETU1E95": "Fretadão - MATRIZ",
  "ETU1I15": "Fretadão - MATRIZ",
  "ETU5I05": "Max Tour Bragança Extrema",
  "ETU5I64": "Max Tour Bragança Extrema",
  "ETU5I67": "Max Tour Bragança Extrema",
  "ETU7866": "Venetur",
  "ETU7869": "Venetur",
  "ETU8315": "Venetur",
  "ETU8317": "Venetur",
  "ETU8322": "Venetur",
  "ETU8323": "Venetur",
  "ETU8326": "Venetur",
  "ETU8327": "Venetur",
  "ETU8329": "Venetur",
  "ETU8335": "Venetur",
  "ETU8336": "Venetur",
  "EUI9210": "Tel Turismo",
  "EUJ1I70": "Karoline E Juliano",
  "EUJ3009": "Viação Jacareí",
  "EUZ2710": "Transguerra",
  "EVA7A68": "Transluz",
  "EVE3H88": "Pantur",
  "EVO9406": "Venetur",
  "EVO9D93": "Venetur",
  "EVO9E21": "Venetur",
  "EVO9F08": "Venetur",
  "EVU3J10": "Venetur",
  "EVU5I91": "Piccolotur Guarulhos",
  "EVU7563": "Piccolotur Taipas",
  "EVU7732": "Piccolotur Guarulhos",
  "EVU7773": "Piccolotur Guarulhos",
  "EVU7774": "Piccolotur Guarulhos",
  "EVU7775": "Piccolotur Guarulhos",
  "EVU7G37": "TaipasTur - Fretadão",
  "EWJ3509": "Venetur",
  "EWJ7C74": "Tel Turismo",
  "EWU2C60": "Micro Tur",
  "EWU2E00": "Pavão Turismo",
  "EWU7A98": "Transluz",
  "EWU7A99": "Transluz",
  "EXE4D72": "Max Tour Bragança Extrema",
  "EXN3A49": "Piccolotur Jundiai",
  "EXO8584": "Tel Turismo",
  "EXS2B11": "Piccolotur Jundiai",
  "EXU4C27": "Transluz",
  "EZL1C24": "Piccolotur Guarulhos",
  "EZL1C87": "Piccolotur Taipas",
  "EZL7132": "Transmimo Jundiai",
  "EZN0960": "Amanhecer",
  "EZN9E11": "Tel Turismo",
  "EZP4262": "Tel Turismo",
  "EZU4F42": "Transmimo Jundiai",
  "EZU4F46": "Transmimo Jundiai",
  "EZU4I46": "Piccolotur Jundiai",
  "EZU9016": "Piccolotur Taipas",
  "EZU9427": "Piccolotur Jundiai",
  "EZU9428": "Piccolotur Jundiai",
  "EZU9443": "Piccolotur Jundiai",
  "EZU9602": "Piccolotur Jundiai",
  "EZU9A11": "Piccolotur Jundiai",
  "EZU9E09": "Piccolotur Guarulhos",
  "EZU9E10": "Piccolotur Guarulhos",
  "EZU9E11": "Piccolotur Guarulhos",
  "EZU9E12": "Piccolotur Guarulhos",
  "EZU9E13": "Piccolotur Guarulhos",
  "EZU9E14": "Bortolotto Fretamento",
  "EZU9E21": "Piccolotur Guarulhos",
  "EZU9E22": "Piccolotur Guarulhos",
  "EZU9E24": "Piccolotur Guarulhos",
  "EZU9E41": "Piccolotur Guarulhos",
  "EZU9G55": "Piccolotur Jundiai",
  "EZU9G59": "Piccolotur Guarulhos",
  "EZU9G75": "Piccolotur Guarulhos",
  "EZU9G78": "Piccolotur Jundiai",
  "EZU9G80": "Piccolotur Guarulhos",
  "EZY3G41": "Transmimo Jundiai",
  "EZZ2F45": "Viação Lima E Silva Ltda",
  "FAC3F83": "Bortolotto Fretamento",
  "FAF0427": "Tamboré",
  "FAT5J20": "GTZ Turismo",
  "FAU8I76": "Tamboré",
  "FAU9772": "Tel Turismo",
  "FAU9G64": "Piracicabana Breda (Santos)",
  "FBQ1987": "Exclusiva Turismo Caieiras e Jundiai",
  "FBU8870": "Viação Lima E Silva Ltda",
  "FBY9835": "Exclusiva Turismo Caieiras e Jundiai",
  "FCE7F91": "Ribeiro Tur",
  "FCE9073": "Tamboré",
  "FCF3G05": "Tamboré",
  "FCI5249": "Exclusiva Turismo Caieiras e Jundiai",
  "FCI5G35": "Tel Turismo",
  "FCI5J91": "Tel Turismo",
  "FCJ5249": "Exclusiva Turismo Caieiras e Jundiai",
  "FCQ5255": "Viação Mimo São José",
  "FCV9E27": "Fretadão - MATRIZ",
  "FCY0J42": "Tel Turismo",
  "FDA5D40": "Dinatur",
  "FDB3078": "Tamboré",
  "FDB7B91": "Max Tour Atibaia",
  "FDC2F86": "Transluz",
  "FDR0079": "Pavão Turismo",
  "FDS7H95": "Fretadão - MATRIZ",
  "FEI1F61": "Piccolotur Guarulhos",
  "FEI1F62": "Piccolotur Guarulhos",
  "FEI2A56": "RealceTur",
  "FEI7C43": "Piccolotur Guarulhos",
  "FEJ7D85": "Aguia Turismo",
  "FEW6D33": "Melhorim Vale Ouro",
  "FFI6173": "Viação Lima E Silva Ltda",
  "FFK3265": "Max Tour Atibaia",
  "FFK8A78": "Transmimo Jundiai",
  "FFN0E86": "Piccolotur Taipas",
  "FFN0E88": "Piccolotur Taipas",
  "FFN0E90": "Piccolotur Taipas",
  "FFN4989": "Piccolotur Taipas",
  "FFN4991": "Piccolotur Taipas",
  "FFN4J83": "Piccolotur Taipas",
  "FFN9550": "AS Service",
  "FFW1C40": "Amanhecer",
  "FFW4632": "Rápido Campinas",
  "FFW5B49": "Tamboré",
  "FGA2A98": "Dinatur",
  "FGG3E13": "Ribeiro Tur",
  "FGL6F75": "Tamboré",
  "FGM2928": "Ribeiro Tur",
  "FGP5A83": "Fretadão - MATRIZ",
  "FGU5J20": "Rio Negro",
  "FGU7C81": "Transmimo Jundiai",
  "FHH8A86": "Bortolotto Fretamento",
  "FHU4C44": "Transmimo Jundiai",
  "FIA1F52": "Transluz",
  "FID5D35": "AS Service",
  "FIG4G07": "Tel Turismo",
  "FIL8H15": "Transmimo Jundiai",
  "FIW7D82": "Transmimo Jundiai",
  "FJB5J96": "Master Bus",
  "FJC2625": "Tel Turismo",
  "FJJ1B19": "Ribeiro Tur",
  "FJK0J15": "Fretadão - MATRIZ",
  "FJP7544": "Ipojucatur Transportes E Turismo Ltda",
  "FJQ3608": "Micro Tur",
  "FJV8F19": "Universal Tour",
  "FJX3B83": "Tamboré",
  "FJX3B93": "Tamboré",
  "FJX5734": "Dinatur",
  "FJX5735": "Dinatur",
  "FJX5736": "Dinatur",
  "FJX5737": "Dinatur",
  "FJX5738": "Dinatur",
  "FJX5746": "Dinatur",
  "FJX5747": "Dinatur",
  "FJX5H33": "Dinatur",
  "FJX8759": "Universal Tour",
  "FKC2566": "Ribeiro Tur",
  "FKG1523": "Aguia Turismo",
  "FKL2E76": "Piccolotur Taipas",
  "FKM8H82": "Tel Turismo",
  "FKP6B12": "Tel Turismo",
  "FKQ7440": "Transguerra",
  "FKS0C53": "Branca de Neve",
  "FLB1I82": "Famatur",
  "FLS8J32": "Transmimo Jundiai",
  "FLZ0E52": "Transmimo Jundiai",
  "FMV8G53": "Transmimo Jundiai",
  "FMW0929": "Piracicabana Breda (Santos)",
  "FMW8G61": "Fretadão - MATRIZ",
  "FMY3I37": "Bortolotto Fretamento",
  "FNA3J67": "Piccolotur Taipas",
  "FNB2E51": "Tel Turismo",
  "FNB8A27": "Transmimo Jundiai",
  "FNF0232": "Ipojucatur Transportes E Turismo Ltda",
  "FNH9720": "Ribeiro Tur",
  "FNJ2032": "Sussantur",
  "FNJ2038": "Sussantur",
  "FNJ2039": "Sussantur",
  "FNJ5102": "Sussantur",
  "FNJ5104": "Sussantur",
  "FNS0B78": "Dinatur",
  "FNS5D15": "Tel Turismo",
  "FNV2E94": "Tel Turismo",
  "FNY3I46": "Tel Turismo",
  "FOB8G66": "Piracicabana Breda (Santos)",
  "FOE2I10": "Aguia Turismo",
  "FOG7B46": "Piccolotur Jundiai",
  "FOJ8985": "Micro Tur",
  "FOL1780": "Sussantur",
  "FON1J71": "Amanhecer",
  "FOP1H54": "Tel Turismo",
  "FOP8108": "Amanhecer",
  "FOR1763": "Tel Turismo",
  "FOU3393": "Transmimo Jundiai",
  "FOY1A81": "Fretadão - MATRIZ",
  "FPA4G09": "Piccolotur Taipas",
  "FPD5J64": "Micro Tur",
  "FPE0B15": "Tel Turismo",
  "FPJ5E88": "Piccolotur Guarulhos",
  "FPJ7I81": "Transguerra",
  "FPL6873": "AS Service",
  "FPN2040": "Sussantur",
  "FPN2041": "Sussantur",
  "FPN2043": "Sussantur",
  "FPN3D56": "Piccolotur Jundiai",
  "FPN4C19": "Rio Negro",
  "FPR8428": "Viação Lima E Silva Ltda",
  "FPS2213": "Branca de Neve",
  "FPT7687": "Sussantur",
  "FPV6C75": "Piccolotur Guarulhos",
  "FPY4H62": "Tel Turismo",
  "FQE7G88": "Aguia Turismo",
  "FQF2J72": "Universal Tour",
  "FQG8925": "Micro Tur",
  "FQH1J80": "Aguia Turismo",
  "FQH9339": "Micro Tur",
  "FQN4E23": "Universal Tour",
  "FQN8F31": "Venetur",
  "FQQ1773": "Viação Mimo São José",
  "FQQ7I43": "Tel Turismo",
  "FQR6G09": "Dinatur",
  "FQS3D62": "Piccolotur Guarulhos",
  "FQW0J25": "Dinatur",
  "FRD6889": "AS Service",
  "FRN9G39": "ByBus",
  "FRP9A46": "ByBus",
  "FRS2I52": "Tel Turismo",
  "FRT6G04": "Tel Turismo",
  "FRV8A81": "Pantur",
  "FRX1I25": "ByBus",
  "FRY2B27": "Max Tour Bragança Extrema",
  "FRY9G03": "Famatur",
  "FRZ1D36": "Micro Tur",
  "FSA3E96": "Venetur",
  "FSB3A53": "AS Service",
  "FSF5093": "Karoline E Juliano",
  "FSF8J82": "Transluz",
  "FSG6E17": "ByBus",
  "FSI5F18": "Ribeiro Tur",
  "FSK4D15": "Branca de Neve",
  "FST9496": "Fretadão - MATRIZ",
  "FSU8G44": "Micro Tur",
  "FSV0570": "AS Service",
  "FSW6854": "AS Service",
  "FSW7356": "Karoline E Juliano",
  "FSX3986": "AS Service",
  "FSY6C13": "Famatur",
  "FTF2E59": "ByBus",
  "FTH4F31": "Famatur",
  "FTH8H70": "Fretadão - MATRIZ",
  "FTK3F76": "Max Tour Bragança Extrema",
  "FTK9E33": "Fretadão - MATRIZ",
  "FTL1A66": "Fretadão - MATRIZ",
  "FTU0083": "AS Service",
  "FTW5101": "AS Service",
  "FUD6J57": "Ribeiro Tur",
  "FUG0237": "Piccolotur Jundiai",
  "FUJ1G51": "Venetur",
  "FUS6498": "Branca de Neve",
  "FUV0H41": "Qualitat",
  "FUW7A79": "Viação Lima E Silva Ltda",
  "FUX0797": "Piccolotur Jundiai",
  "FUZ7744": "AS Service",
  "FVB6B44": "Piccolotur Guarulhos",
  "FVC1C32": "Pantur",
  "FVD5B73": "Dinatur",
  "FVF0706": "Fretadão - MATRIZ",
  "FVG9I41": "Piccolotur Taipas",
  "FVI8A01": "ByBus",
  "FVJ8J69": "Venetur",
  "FVK8C97": "Transmimo Jundiai",
  "FVK8H79": "Universal Tour",
  "FVN7G46": "Max Tour Bragança Extrema",
  "FVO4F14": "Universal Tour",
  "FVP2B06": "Venetur",
  "FVR5506": "AS Service",
  "FVS6E24": "ByBus",
  "FVY8J03": "Tel Turismo",
  "FVZ8427": "Micro Tur",
  "FWB5388": "Pavão Turismo",
  "FWD3211": "Branca de Neve",
  "FWH7B16": "Piccolotur Guarulhos",
  "FWL0D05": "Ipojucatur Transportes E Turismo Ltda",
  "FWL6H86": "Fretadão - MATRIZ",
  "FWL9A66": "Venetur",
  "FWM1I37": "Piracicabana Breda (Santos)",
  "FWP2583": "Tel Turismo",
  "FWR8C83": "Piccolotur Jundiai",
  "FWZ8J27": "Qualitat",
  "FXG0120": "Transguerra",
  "FXG4B43": "Piccolotur Taipas",
  "FXH7G63": "Aguia Turismo",
  "FXI0J99": "Universal Tour",
  "FXJ8E81": "Transmimo Jundiai",
  "FXK2G82": "Piccolotur Taipas",
  "FXR8C08": "Rio Negro",
  "FXR9117": "Piccolotur Taipas",
  "FXS0E71": "Piracicabana Breda (Santos)",
  "FXS0H78": "Universal Tour",
  "FXS7H79": "Piccolotur Guarulhos",
  "FXV9B90": "Piccolotur Taipas",
  "FXW4664": "Tel Turismo",
  "FXW4G32": "Tel Turismo",
  "FXZ6F26": "Piccolotur Taipas",
  "FXZ6J30": "Fretadão - MATRIZ",
  "FYD6G76": "Exclusiva Turismo Caieiras e Jundiai",
  "FYD7C92": "Transmimo Jundiai",
  "FYE0B69": "Piccolotur Taipas",
  "FYF1I47": "Piccolotur Taipas",
  "FYG1E56": "Piracicabana Breda (Santos)",
  "FYH1F21": "Transluz",
  "FYI4G11": "Qualitat",
  "FYJ8F93": "Tel Turismo",
  "FYK6F21": "Transmimo Jundiai",
  "FYU0E33": "ByBus",
  "FYV5A69": "Pantur",
  "FYV5I06": "Master Bus",
  "FYY9G21": "Amanhecer",
  "FZC5A76": "Tel Turismo",
  "FZC9E96": "ByBus",
  "FZH0E16": "Pavão Turismo",
  "FZM8F06": "Ipojucatur Transportes E Turismo Ltda",
  "FZR1H38": "Piccolotur Guarulhos",
  "FZU3G24": "Micro Tur",
  "FZW4J61": "Tel Turismo",
  "GAB8346": "Piracicabana Breda (Santos)",
  "GAF4D94": "Universal Tour",
  "GAF6371": "Branca de Neve",
  "GAH5797": "AS Service",
  "GAH9E04": "Piracicabana Breda (Santos)",
  "GAL3C34": "Fretadão - MATRIZ",
  "GAO2F46": "Piracicabana Breda (Santos)",
  "GAO7H42": "Transguerra",
  "GAV4I01": "Master Bus",
  "GAW3C26": "Max Tour Bragança Extrema",
  "GAW5E34": "Famatur",
  "GAZ1F39": "Melhorim Vale Ouro",
  "GAZ4B46": "Fretadão - MATRIZ",
  "GBA1D76": "Karoline E Juliano",
  "GBA8968": "Transmimo Jundiai",
  "GBC7C12": "ByBus",
  "GBE5E76": "Piracicabana Breda (Santos)",
  "GBI4F72": "Piccolotur Taipas",
  "GBJ6A72": "Transmimo Jundiai",
  "GBM2308": "AS Service",
  "GBM6J86": "Max Tour Bragança Extrema",
  "GBR4E83": "Melhorim Vale Ouro",
  "GBR8J37": "Max Tour Poços",
  "GBV9C69": "Branca de Neve",
  "GBV9I39": "Viação Lima E Silva Ltda",
  "GCL1H78": "Transmimo Jundiai",
  "GCM1B85": "Transmimo Valinhos",
  "GCM4547": "AS Service",
  "GCN1100": "Micro Tur",
  "GCO0226": "Pavão Turismo",
  "GCO0233": "Max Tour Atibaia",
  "GCO0C31": "Pavão Turismo",
  "GCO2I86": "ByBus",
  "GCS1H33": "Piracicabana Breda (Santos)",
  "GCY2C51": "Piracicabana Breda (Santos)",
  "GDB8C44": "Qualitat",
  "GDC1H69": "Aguia Turismo",
  "GDC2026": "AS Service",
  "GDC3B77": "Piccolotur Jundiai",
  "GDJ3H35": "AS Service",
  "GDL7I86": "Ribeiro Tur",
  "GDM4529": "Piccolotur Jundiai",
  "GDM4B12": "Piracicabana Breda (Santos)",
  "GDM7A65": "Transmimo Jundiai",
  "GDN1E43": "Max Tour Atibaia",
  "GDN8H64": "Transmimo Jundiai",
  "GDO2G55": "Tel Turismo",
  "GDP2499": "Piccolotur Taipas",
  "GDT0D64": "Max Tour Bragança Extrema",
  "GDY2J90": "Aguia Turismo",
  "GDY3835": "Transmimo Jundiai",
  "GDZ3576": "AS Service",
  "GEA0H93": "Piracicabana Breda (Santos)",
  "GED7D53": "Max Tour Bragança Extrema",
  "GED9E53": "Piracicabana Breda (Santos)",
  "GEF8B36": "Piccolotur Jundiai",
  "GEL7F94": "Piracicabana Breda (Santos)",
  "GEP2F54": "ByBus",
  "GEP4736": "Transmimo Jundiai",
  "GEQ5377": "Transmimo Jundiai",
  "GEU0F12": "Max Tour Bragança Extrema",
  "GEV7G84": "Viação Jacareí",
  "GEV8367": "Transmimo Jundiai",
  "GEY2A26": "Transluz",
  "GEZ7608": "Transmimo Jundiai",
  "GEZ7A25": "Transluz",
  "GFB4C66": "Master Bus",
  "GFC3A73": "Tel Turismo",
  "GFC5C74": "Amanhecer",
  "GFD7C56": "Piccolotur Jundiai",
  "GFL2857": "AS Service",
  "GFL5465": "Tel Turismo",
  "GFM3J21": "Max Tour Bragança Extrema",
  "GFS7D66": "ByBus",
  "GFS9923": "AS Service",
  "GFU4767": "Piracicabana Breda (Santos)",
  "GFV6E15": "Famatur",
  "GFW7F97": "Piccolotur Taipas",
  "GFX5877": "Universal Tour",
  "GGA8972": "Transmimo Jundiai",
  "GGI5I71": "Transluz",
  "GGI7E32": "Piracicabana Breda (Santos)",
  "GGJ5J88": "Amanhecer",
  "GGM1I83": "Transmimo Jundiai",
  "GGN8G01": "Max Tour Bragança Extrema",
  "GGR0D38": "Piccolotur Jundiai",
  "GGR9326": "Transmimo Jundiai",
  "GGT8F50": "Famatur",
  "GGU0234": "AS Service",
  "GGV0D48": "Branca de Neve",
  "GGZ6078": "Piccolotur Taipas",
  "GHC6E17": "Piracicabana Breda (Santos)",
  "GHD8840": "Branca de Neve",
  "GHE4G96": "Piracicabana Breda (Santos)",
  "GHE5A35": "Fretadão - MATRIZ",
  "GHF2E05": "Piracicabana Breda (Santos)",
  "GHG8I92": "Transmimo Jundiai",
  "GHH9C74": "Max Tour Bragança Extrema",
  "GHI4C01": "Piracicabana Breda (Santos)",
  "GHR4I62": "Piracicabana Breda (Santos)",
  "GHR6177": "Piccolotur Jundiai",
  "GHR7G44": "Branca de Neve",
  "GHS9579": "Tel Turismo",
  "GHU7F47": "Master Bus",
  "GHX1I89": "AS Service",
  "GIJ0898": "AS Service",
  "GIO8G49": "Transmimo Jundiai",
  "GIO8I97": "Master Bus",
  "GIQ3D64": "Fretadão - MATRIZ",
  "GIR8J36": "Piracicabana Breda (Santos)",
  "GIS6E14": "Qualitat",
  "GIU7A12": "Transmimo Jundiai",
  "GIU9J24": "Piracicabana Breda (Santos)",
  "GIV5729": "Piccolotur Guarulhos",
  "GIV7J85": "Transmimo Jundiai",
  "GIZ9G07": "Max Tour Bragança Extrema",
  "GJA3B17": "Amanhecer",
  "GJB4E51": "Piracicabana Breda (Santos)",
  "GJC6F52": "Tel Turismo",
  "GJD9F83": "Transmimo Jundiai",
  "GJD9G55": "Transmimo Jundiai",
  "GJF7J81": "Transmimo Jundiai",
  "GJS6B46": "Piracicabana Breda (Santos)",
  "GJT3I84": "Piracicabana Breda (Santos)",
  "GJT9A67": "Universal Tour",
  "GJW5I37": "Piccolotur Guarulhos",
  "GJW9H05": "Piracicabana Breda (Santos)",
  "GJX3H21": "Piracicabana Breda (Santos)",
  "GKA6A21": "Transmimo Jundiai",
  "GKC3141": "Tel Turismo",
  "GKG7B56": "Fretadão - MATRIZ",
  "GKG9C46": "Piracicabana Breda (Santos)",
  "GSQ3G67": "Transmimo Jundiai",
  "GYS6689": "Transluz",
  "GYS6I97": "Venetur",
  "HFF9759": "RealceTur",
  "HGJ6E80": "Fretadão - MATRIZ",
  "HIT9F50": "Transluz",
  "HJA32110": "Pantur",
  "HJF0E95": "Max Tour Atibaia",
  "HJR9416": "Max Tour Bragança Extrema",
  "HJZ6E72": "Max Tour Atibaia",
  "HJZ6E87": "Max Tour Atibaia",
  "HOA1533": "Viação Minas Gerais",
  "HOA1580": "Viação Minas Gerais",
  "HRO5856": "Fretadão - MATRIZ",
  "HTP1I45": "Aguia Turismo",
  "HTP2E19": "Venetur",
  "ISY5481": "Fretadão - MATRIZ",
  "ISY5483": "Fretadão - MATRIZ",
  "ISY5484": "Fretadão - MATRIZ",
  "ISY9434": "Fretadão - MATRIZ",
  "ITU7897": "Fretadão - MATRIZ",
  "IUR5105": "Fretadão - MATRIZ",
  "IUR5B06": "Fretadão - MATRIZ",
  "IVT5G88": "Fretadão - MATRIZ",
  "IXE5279": "Fretadão - MATRIZ",
  "IYK5J58": "Fretadão - MATRIZ",
  "JAG1D34": "Fretadão - MATRIZ",
  "JAG9F72": "Max Tour Bragança Extrema",
  "JAQ2G21": "Fretadão - MATRIZ",
  "JAW4A08": "Fretadão - MATRIZ",
  "JAW8B05": "Fretadão - MATRIZ",
  "KOP1882": "Ribeiro Tur",
  "KOW3H10": "Max Tour Bragança Extrema",
  "KPK2G70": "Piccolotur Jundiai",
  "KPR2I75": "Fretadão - MATRIZ",
  "KPZ4I18": "Transmimo Jundiai",
  "KQB7D70": "Fretadão - MATRIZ",
  "KQK6I73": "Piracicabana Breda (Santos)",
  "KQK6I77": "Piracicabana Breda (Santos)",
  "KQQ7H61": "Universal Tour",
  "KRB8493": "Fretadão - MATRIZ",
  "KRH4G47": "Max Tour Bragança Extrema",
  "KRZ6H29": "Bortolotto Fretamento",
  "KVH9D17": "RealceTur",
  "KVW5A99": "Ribeiro Tur",
  "KWK8B90": "Venetur",
  "KWL6I56": "Venetur",
  "KWP6I26": "Famatur",
  "KWP6I29": "Famatur",
  "KWP6I31": "Famatur",
  "KWT8I43": "Transmimo Jundiai",
  "KWW3G32": "Tamboré",
  "KWW6E35": "Venetur",
  "KXB7J49": "Melhorim Vale Ouro",
  "KXB7J61": "Melhorim Vale Ouro",
  "KXQ6J44": "Pantur",
  "KYQC64": "Max Tour Atibaia",
  "KZC9E27": "Max Tour Bragança Extrema",
  "KZG8H82": "Bortolotto Fretamento",
  "KZI9B58": "Amanhecer",
  "LLX3I24": "Tamboré",
  "LMB8A70": "Venetur",
  "LMD2J94": "Transluz",
  "LMF9H45": "Transmimo Jundiai",
  "LMJ7G44": "ByBus",
  "LMJ9364": "Fretadão - MATRIZ",
  "LMN2C17": "Amanhecer",
  "LMR4E30": "Viação Lima E Silva Ltda",
  "LQJ2G90": "Pantur",
  "LQY5C82": "Tamboré",
  "LRD3893": "Transmimo Jundiai",
  "LRU6E77": "Piccolotur Guarulhos",
  "LRU6E81": "Piccolotur Guarulhos",
  "LRZ7B94": "Ribeiro Tur",
  "LSE4F01": "Venetur",
  "LSZ5I19": "Piracicabana Breda (Santos)",
  "LTG7A98": "Max Tour Atibaia",
  "LTK8C08": "Max Tour Atibaia",
  "MKG8G50": "Pantur",
  "MKW9E03": "Amanhecer",
  "MLP8G00": "Aguia Turismo",
  "MWS8B64": "Pantur",
  "MWU4C81": "Mac Turismo",
  "OCX7E18": "Melhorim Vale Ouro",
  "OCX8G28": "Melhorim Vale Ouro",
  "OIE0G97": "ByBus",
  "OJF3J76": "Ribeiro Tur",
  "OOQ8H70": "Universal Tour",
  "OOS7A14": "Karoline E Juliano",
  "OQM4446": "Viação Lima E Silva Ltda",
  "OQO5062": "Venetur",
  "OQO5067": "Venetur",
  "OQO5084": "Venetur",
  "OQO5089": "Venetur",
  "OQO5095": "Venetur",
  "OQO5110": "Venetur",
  "OQQ4G54": "Universal Tour",
  "OQV5A35": "Venetur",
  "OTV1G25": "Ribeiro Tur",
  "OVS2F17": "Universal Tour",
  "OWZ2G00": "RealceTur",
  "OXG2795": "Fretadão - MATRIZ",
  "OXG2H95": "Fretadão - MATRIZ",
  "OYJ5B47": "Transguerra",
  "PAT1H04": "Fretadão - MATRIZ",
  "PBB1A13": "Aguia Turismo",
  "PFZ1177": "Ribeiro Tur",
  "PGL8D62": "Fretadão - MATRIZ",
  "PIM1923": "Fretadão - MATRIZ",
  "PJF5B95": "Fretadão - MATRIZ",
  "PKU4G70": "Ribeiro Tur",
  "PLB9C69": "Karoline E Juliano",
  "PMT9753": "Fretar",
  "PNE8H82": "Fretar",
  "PNL2G08": "Transguerra",
  "PNU8E81": "Tamboré",
  "POF6668": "Fretar",
  "POT9879": "Fretar",
  "PPJ2E66": "Melhorim Vale Ouro",
  "PPU2D07": "Melhorim Vale Ouro",
  "PPU7E22": "Melhorim Vale Ouro",
  "PQS3B66": "Viação Lima E Silva Ltda",
  "PQS3D46": "Viação Lima E Silva Ltda",
  "PQS3I86": "Viação Lima E Silva Ltda",
  "PQU6H84": "Viação Lima E Silva Ltda",
  "PRV9H07": "Max Tour Bragança Extrema",
  "PRV9J57": "Max Tour Bragança Extrema",
  "PRZ7184": "Transmimo Jundiai",
  "PTP1I92": "Mac Turismo",
  "PTR5J90": "Melhorim Vale Ouro",
  "PTT7C04": "Melhorim Vale Ouro",
  "PWA6H86": "Famatur",
  "PXL2C63": "Amanhecer",
  "PZF1C55": "Karoline E Juliano",
  "QAH1G49": "Fretadão - MATRIZ",
  "QAH1J24": "Melhorim Vale Ouro",
  "QDN2D35": "Melhorim Vale Ouro",
  "QDT6I61": "Max Tour Atibaia",
  "QDT7F71": "Max Tour Atibaia",
  "QEF4F85": "Melhorim Vale Ouro",
  "QEK9F57": "Transmimo Jundiai",
  "QEV0B90": "Melhorim Vale Ouro",
  "QLE6J30": "Ribeiro Tur",
  "QNO7C42": "Universal Tour",
  "QNW4781": "Viação Minas Gerais",
  "QNW9D96": "Max Tour Atibaia",
  "QOS0G28": "Melhorim Vale Ouro",
  "QQN9B78": "Amanhecer",
  "QQR7098": "Transmimo Jundiai",
  "QQR7191": "Fretadão - MATRIZ",
  "QQT8930": "Transmimo Jundiai",
  "QQW5830": "Transmimo Jundiai",
  "QRC1G91": "Transguerra",
  "QRG2I18": "Melhorim Vale Ouro",
  "QRL0J82": "Melhorim Vale Ouro",
  "QRM1J93": "Melhorim Vale Ouro",
  "QSQ9F02": "Piracicabana Breda (Santos)",
  "QSS6I49": "Fretadão - MATRIZ",
  "QSS7I99": "Transmimo Jundiai",
  "QSU9G21": "Transmimo Jundiai",
  "QSW4F22": "Tel Turismo",
  "QSX0J29": "Transmimo Jundiai",
  "QSY8H85": "Transmimo Jundiai",
  "QSZ3C50": "Amanhecer",
  "QSZ5C32": "Transmimo Jundiai",
  "QVB6A27": "Carvalhos Tur",
  "QVJ9H63": "Carvalhos Tur",
  "QVL9C57": "Max Tour Bragança Extrema",
  "QVL9C77": "Max Tour Bragança Extrema",
  "RFG7G80": "Viação Minas Gerais",
  "RFP3E02": "Fretadão - MATRIZ",
  "RHG3G37": "G3 Transportadora",
  "RIQ0J72": "Tamboré",
  "RIR2C80": "Pavão Turismo",
  "RIS1B08": "Tamboré",
  "RIS4E83": "Dinatur",
  "RIX6H37": "Max Tour Bragança Extrema",
  "RIY4A03": "Tamboré",
  "RJD1F92": "Pavão Turismo",
  "RJG0J70": "Tamboré",
  "RJI2B70": "Pavão Turismo",
  "RJI3J01": "Max Tour Bragança Extrema",
  "RJJ0J78": "Tamboré",
  "RJM4F59": "Dinatur",
  "RJU2C46": "Pavão Turismo",
  "RJY3G79": "Tamboré",
  "RKB2A62": "Pavão Turismo",
  "RKB4B19": "Dinatur",
  "RKE4B06": "Tamboré",
  "RKH0D64": "Fretadão - MATRIZ",
  "RKI4D38": "Tamboré",
  "RKN0B50": "Max Tour Atibaia",
  "RKN0B51": "Max Tour Atibaia",
  "RMS8A42": "Viação Minas Gerais",
  "RMT2C10": "Fretadão - MATRIZ",
  "RMT2C69": "Viação Minas Gerais",
  "RMZ1A45": "Amanhecer",
  "RNB5A24": "Max Tour Bragança Extrema",
  "RNB5C83": "Max Tour Bragança Extrema",
  "RNB5D18": "Max Tour Bragança Extrema",
  "RNB5D68": "Max Tour Bragança Extrema",
  "RNB5E23": "Max Tour Bragança Extrema",
  "RNB5E89": "Max Tour Bragança Extrema",
  "RNB5F40": "Max Tour Bragança Extrema",
  "RNB5F48": "Max Tour Bragança Extrema",
  "RNG6B57": "Max Tour Bragança Extrema",
  "RNG6B75": "Max Tour Bragança Extrema",
  "RNG6B94": "Max Tour Bragança Extrema",
  "RNM4E20": "Max Tour Bragança Extrema",
  "RNP0I21": "Fretadão - MATRIZ",
  "RNY6F35": "Viação Minas Gerais",
  "RNY6F43": "Viação Minas Gerais",
  "RNY9J86": "Viação Minas Gerais",
  "ROE7A56": "Melhorim Vale Ouro",
  "RPA0J05": "Transmimo Jundiai",
  "RPA3C04": "Transmimo Jundiai",
  "RSE8F94": "Fretadão - MATRIZ",
  "RUA2D88": "Amanhecer",
  "RUU5E30": "Viação Minas Gerais",
  "RVT4D44": "Max Tour Poços",
  "RVW3F88": "Max Tour Bragança Extrema",
  "RVX3B53": "Max Tour Bragança Extrema",
  "RVZ0C31": "Max Tour Bragança Extrema",
  "RVZ0C49": "Max Tour Bragança Extrema",
  "RWJ8I21": "Fretadão - MATRIZ",
  "RWK7G98": "Carvalhos Tur",
  "RWQ5B88": "Carvalhos Tur",
  "RWV7B97": "Carvalhos Tur",
  "RWZ1A49": "Carvalhos Tur",
  "RXB4A78": "Carvalhos Tur",
  "RXC4G30": "Carvalhos Tur",
  "SBF6C43": "Fretadão - MATRIZ",
  "SCQ8J39": "Fretadão - MATRIZ",
  "SCT5D56": "Fretadão - MATRIZ",
  "SCT6D26": "Fretadão - MATRIZ",
  "SDH2G04": "Fretadão - MATRIZ",
  "SEF1A05": "G3 Transportadora",
  "SEF5A77": "G3 Transportadora",
  "SEF5H77": "G3 Transportadora",
  "SEF7H73": "G3 Transportadora",
  "SEG3D35": "G3 Transportadora",
  "SEG3G37": "G3 Transportadora",
  "SEG3H37": "G3 Transportadora",
  "SEG7F75": "G3 Transportadora",
  "SEG7G75": "G3 Transportadora",
  "SEM3G37": "G3 Transportadora",
  "SEM5A07": "G3 Transportadora",
  "SEM6G33": "G3 Transportadora",
  "SEN1A50": "G3 Transportadora",
  "SEN1A53": "G3 Transportadora",
  "SEN1A57": "G3 Transportadora",
  "SEN3G36": "G3 Transportadora",
  "SEN3G37": "G3 Transportadora",
  "SEN6G77": "G3 Transportadora",
  "SEN7G33": "G3 Transportadora",
  "SFE6G33": "G3 Transportadora",
  "SFG3G33": "G3 Transportadora",
  "SFG3G77": "G3 Transportadora",
  "SFU4A85": "Melhorim Vale Ouro",
  "SFX9H45": "Melhorim Vale Ouro",
  "SFY4D80": "Melhorim Vale Ouro",
  "SFY6F00": "Melhorim Vale Ouro",
  "SGM1G88": "Melhorim Vale Ouro",
  "SGM1G89": "Melhorim Vale Ouro",
  "SHC4C55": "Max Tour Bragança Extrema",
  "SHG1J78": "Viação Minas Gerais",
  "SHZ2E09": "Transmimo Jundiai",
  "SIK3E18": "Max Tour Bragança Extrema",
  "SIK3E31": "Max Tour Bragança Extrema",
  "SIK3E34": "Max Tour Bragança Extrema",
  "SIK3E36": "Max Tour Bragança Extrema",
  "SIN6J26": "Transmimo Jundiai",
  "SIN9E33": "Transmimo Jundiai",
  "SIO4I58": "Transmimo Jundiai",
  "SIP8H13": "Viação Minas Gerais",
  "SIR4B47": "Max Tour Bragança Extrema",
  "SIS4B03": "Max Tour Bragança Extrema",
  "SJA7I56": "Max Tour Bragança Extrema",
  "SJC9F54": "Max Tour Bragança Extrema",
  "SJC9G53": "Max Tour Bragança Extrema",
  "SLZ8A83": "Carvalhos Tur",
  "SRM2C23": "Piccolotur Guarulhos",
  "SRT2B58": "Dinatur",
  "SRV2G52": "Dinatur",
  "SRV7F50": "Fretadão - MATRIZ",
  "SRV8C61": "Dinatur",
  "SRW5D45": "Fretadão - MATRIZ",
  "SRW5D47": "Fretadão - MATRIZ",
  "SSR7H23": "Piccolotur Jundiai",
  "SST8D45": "Gold Turismo",
  "SSU2C99": "Piccolotur Jundiai",
  "SSU6G38": "AS Service",
  "SSX2J29": "Ribeiro Tur",
  "SSY1A89": "Max Tour Bragança Extrema",
  "SSZ4C40": "Master Bus",
  "STB3I78": "Transmimo Jundiai",
  "STE4F28": "Transmimo Jundiai",
  "STE7D90": "Transmimo Jundiai",
  "STG1D47": "Universal Tour",
  "STG4E61": "Amanhecer",
  "STJ2A41": "Master Bus",
  "STK2E20": "Master Bus",
  "STM0E05": "Ribeiro Tur",
  "STM2G60": "Transmimo Jundiai",
  "STN7A73": "Piracicabana Breda (Santos)",
  "STO3F68": "Max Tour Bragança Extrema",
  "STP3I93": "Viação Jacareí",
  "STP5F58": "Fretadão - MATRIZ",
  "STQ0J07": "Amanhecer",
  "STQ3B17": "Aguia Turismo",
  "STT4H84": "Transmimo Jundiai",
  "STU6G06": "Piccolotur Guarulhos",
  "STX2I88": "Qualitat",
  "STX9J31": "Piracicabana Breda (Santos)",
  "STY0C86": "Piracicabana Breda (Santos)",
  "STY5J35": "Piracicabana Breda (Santos)",
  "SUA2D57": "Aguia Turismo",
  "SUD0D16": "Transmimo Jundiai",
  "SUD0D27": "Master Bus",
  "SUE4C04": "Piccolotur Taipas",
  "SUF0I31": "Ribeiro Tur",
  "SUH0C66": "Qualitat",
  "SUH2J57": "Transmimo Jundiai",
  "SUH3J37": "Piccolotur Jundiai",
  "SUI7F36": "Transmimo Jundiai",
  "SUJ0I33": "Piccolotur Jundiai",
  "SUJ1I82": "Transmimo Jundiai",
  "SUK4C47": "Piracicabana Breda (Santos)",
  "SUL1G15": "Max Tour Bragança Extrema",
  "SUL7J91": "Transmimo Jundiai",
  "SUM9G74": "Master Bus",
  "SUN3C20": "Universal Tour",
  "SUQ7J76": "Gatti",
  "SUW3G44": "Qualitat",
  "SUW4A03": "Master Bus",
  "SUW8G62": "Piracicabana Breda (Santos)",
  "SUW8J94": "Piracicabana Breda (Santos)",
  "SUX0E49": "RealceTur",
  "SUY3F62": "Piracicabana Breda (Santos)",
  "SUZ4E50": "AS Service",
  "SUZ8A10": "Fretadão - MATRIZ",
  "SUZ9I81": "Piccolotur Guarulhos",
  "SVA7B67": "Bortolotto Fretamento",
  "SVA7F39": "Piccolotur Guarulhos",
  "SVC4J66": "Amanhecer",
  "SVE1H02": "Piracicabana Breda (Santos)",
  "SVE6A73": "Transmimo Jundiai",
  "SVF8H97": "Transmimo Jundiai",
  "SVI0E24": "Tamboré",
  "SVI3A04": "Exclusiva Turismo - Campinas",
  "SVI4G48": "Amanhecer",
  "SVJ6E59": "Transmimo Valinhos",
  "SVK0A26": "Ribeiro Tur",
  "SVK0J09": "Piccolotur Jundiai",
  "SVL7I10": "Viação Jacareí",
  "SVL7I76": "Transmimo Jundiai",
  "SVL9I43": "Piracicabana Breda (Santos)",
  "SVM9J59": "Piccolotur Jundiai",
  "SVN4E64": "Piccolotur Jundiai",
  "SVN5A99": "Master Bus",
  "SVO1D61": "Ribeiro Tur",
  "SVR2A97": "Transmimo Jundiai",
  "SVR9H62": "Piccolotur Jundiai",
  "SVT1A95": "Dinatur",
  "SVT9I52": "Piracicabana Breda (Santos)",
  "SVV4C02": "Master Bus",
  "SVV6B95": "Branca de Neve",
  "SVV9G89": "Transmimo Jundiai",
  "SVW0J70": "Piccolotur Guarulhos",
  "SVW5A29": "Exclusiva Turismo - Campinas",
  "SVY5E03": "Ribeiro Tur",
  "SVZ0E51": "Transmimo Jundiai",
  "SWA2G34": "Master Bus",
  "SWA9D90": "Piccolotur Taipas",
  "SWC0D07": "Transmimo Jundiai",
  "SWC4J09": "AS Service",
  "SWD3A25": "Transmimo Jundiai",
  "SWE1H57": "Piccolotur Taipas",
  "SWG0D11": "Gold Turismo",
  "SWG1I65": "Transmimo Jundiai",
  "SWH3C88": "Ribeiro Tur",
  "SWH5D54": "Fretadão - MATRIZ",
  "SWI0C31": "Piracicabana Breda (Santos)",
  "SWI1I25": "Piccolotur Jundiai",
  "SWK4I76": "Transmimo Jundiai",
  "SWN0D11": "Gold Turismo",
  "SWN0G23": "AS Service",
  "SWN6A95": "Transmimo Jundiai",
  "SWQ2D81": "Piracicabana Breda (Santos)",
  "SWQ4D40": "AS Service",
  "SWR1I58": "Piccolotur Jundiai",
  "SWS4I55": "Piccolotur Jundiai",
  "SWS5D62": "Transmimo Jundiai",
  "SWU4F28": "Ribeiro Tur",
  "SWV9J27": "Branca de Neve",
  "SWY0E33": "Piccolotur Jundiai",
  "SYN6A23": "Max Tour Poços",
  "SYN6A29": "Max Tour Poços",
  "SZL8B13": "Carvalhos Tur",
  "SZP3A07": "Carvalhos Tur",
  "TAI3G37": "G3 Transportadora",
  "TAY7G37": "G3 Transportadora",
  "TCA3F80": "Viação Minas Gerais",
  "TCO2F21": "Max Tour Bragança Extrema",
  "TDW5E14": "Fretadão - MATRIZ",
  "TGC5D42": "Fretadão - MATRIZ",
  "TGY2J20": "Fretadão - MATRIZ",
  "THP8H77": "Tamboré",
  "THV5J80": "Fretadão - MATRIZ",
  "THZ3J77": "Fretar",
  "THZ4J77": "Fretar",
  "TIB7I30": "Fretadão - MATRIZ",
  "TIB8G20": "Fretadão - MATRIZ",
  "TIF4J77": "Fretar",
  "TIL8F34": "Fretadão - MATRIZ",
  "TIN4J02": "Fretadão - MATRIZ",
  "TIN6C32": "Fretadão - MATRIZ",
  "TIN7B62": "Fretadão - MATRIZ",
  "TIO8E18": "Piccolotur Jundiai",
  "TIQ2A23": "Transmimo Jundiai",
  "TIQ8G61": "Gold Turismo",
  "TIS0D63": "Gold Turismo",
  "TIS4F58": "Gold Turismo",
  "TIT3F12": "Tel Turismo",
  "TIU9A20": "Gold Turismo",
  "TIU9E40": "Gold Turismo",
  "TIU9G76": "Tel Turismo",
  "TIU9J30": "Gold Turismo",
  "TIV3H22": "Qualitat",
  "TIV6H76": "Amanhecer",
  "TIX3F41": "Qualitat",
  "TIY3J11": "Gold Turismo",
  "TIY8E13": "Gold Turismo",
  "TIY8J44": "Gold Turismo",
  "TIZ3G62": "Transmimo Jundiai",
  "TIZ8H50": "Master Bus",
  "TJA1G03": "Gatti",
  "TJA2F03": "Ribeiro Tur",
  "TJF2C32": "Transmimo Jundiai",
  "TJF4I71": "Piccolotur Taipas",
  "TJG5G62": "Piracicabana Breda (Santos)",
  "TJG8E23": "Piracicabana Breda (Santos)",
  "TJH3E75": "Transmimo Jundiai",
  "TJI5H54": "Gold Turismo",
  "TJJ0E96": "Karoline E Juliano",
  "TJN8A08": "Karoline E Juliano",
  "TJO9G79": "Tel Turismo",
  "TJP2A99": "Qualitat",
  "TJP5J07": "GTZ Turismo",
  "TJQ0I12": "Piccolotur Jundiai",
  "TJQ4D00": "Qualitat",
  "TJQ7G44": "Tel Turismo",
  "TJS4C71": "GTZ Turismo",
  "TJS8H22": "Transmimo Jundiai",
  "TJT7C44": "Qualitat",
  "TJW0B37": "Transmimo Jundiai",
  "TJW6A35": "Famatur",
  "TJX4E40": "Qualitat",
  "TJY2J66": "Piccolotur Jundiai",
  "TKC1A00": "Viação Jacareí",
  "TKC7J52": "Gold Turismo",
  "TKC9B16": "Famatur",
  "TKD7D56": "AS Service",
  "TKE7C76": "Transmimo Jundiai",
  "TKF6J80": "Amanhecer",
  "TKG1B48": "Famatur",
  "TKG3A73": "Piracicabana Breda (Santos)",
  "TKG7I31": "Piccolotur Taipas",
  "TKI0C31": "Gold Turismo",
  "TKI4C00": "Piccolotur Jundiai",
  "TKI5B44": "Qualitat",
  "TKJ4E23": "AS Service",
  "TKK1I57": "Famatur",
  "TKL2J23": "Famatur",
  "TKL7D20": "Famatur",
  "TKO1E24": "Qualitat",
  "TKO3J11": "Gatti",
  "TKO9F11": "Qualitat",
  "TKP6F38": "Piccolotur Guarulhos",
  "TKP7F67": "Gatti",
  "TKR8F04": "Max Tour Bragança Extrema",
  "TKS7A09": "Fretadão - MATRIZ",
  "TKV7B99": "Master Bus",
  "TKV8G02": "AS Service",
  "TKV9J94": "Piccolotur Jundiai",
  "TKX2C05": "Piracicabana Breda (Santos)",
  "TKZ2G55": "Tel Turismo",
  "TLB5D67": "Master Bus",
  "TLB9C14": "Ipojucatur Transportes E Turismo Ltda",
  "TLB9I93": "Master Bus",
  "TLC2J66": "Tel Turismo",
  "TLE5I73": "Tel Turismo",
  "TLE8H88": "Transmimo Jundiai",
  "TLG8I89": "Transmimo Jundiai",
  "TLI0J10": "Piccolotur Jundiai",
  "TLI3H93": "Piccolotur Jundiai",
  "TLI7C31": "Gold Turismo",
  "TLI7I38": "Master Bus",
  "TLM2J29": "Amanhecer",
  "TLM8A21": "Gold Turismo",
  "TLS2G33": "Tel Turismo",
  "TLS3H35": "Piccolotur Taipas",
  "TLS3J95": "Transmimo Jundiai",
  "TLU1J15": "Gold Turismo",
  "TLU6A44": "Amanhecer",
  "TLV7D34": "Piracicabana Breda (Santos)",
  "TLW1B85": "Piracicabana Breda (Santos)",
  "TLW5C18": "Tel Turismo",
  "TLW8E61": "Transmimo Jundiai",
  "TLX8J58": "Piccolotur Taipas",
  "TLY2A30": "Viação Jacareí",
  "TLZ0J17": "Transmimo Jundiai",
  "TMA2J99": "Transmimo Jundiai",
  "TMA9A93": "Qualitat",
  "TMB0B90": "Viação Jacareí",
  "TMB3B44": "Master Bus",
  "TMB7A56": "Micro Tur",
  "TMC5B47": "Master Bus",
  "TME1E39": "Famatur",
  "TME4I27": "Micro Tur",
  "TMF2E02": "Transmimo Jundiai",
  "TMF7E73": "Gatti",
  "TMF8J08": "Amanhecer",
  "TMG9A98": "Universal Tour",
  "TMH7D61": "Transmimo Jundiai",
  "TMI2B12": "Transmimo Jundiai",
  "TMI7C42": "Transmimo Jundiai",
  "TMI8F62": "Universal Tour",
  "TMJ6F56": "Tamboré",
  "TTE7B20": "Tamboré",
  "TTN0A84": "Fretadão - MATRIZ",
  "TVB7B25": "Mac Turismo",
  "TXR5D37": "Max Tour Bragança Extrema",
  "TXR5D47": "Max Tour Bragança Extrema",
  "TXR5D50": "Max Tour Bragança Extrema",
  "TXR5D52": "Max Tour Bragança Extrema",
  "TXR5D56": "Max Tour Bragança Extrema",
  "TXU6C05": "Max Tour Bragança Extrema",
  "UDA4J36": "Viação Jacareí",
  "UDA6B02": "Transmimo Jundiai",
  "UDB2E29": "Famatur",
  "UDC4D92": "Piracicabana Breda (Santos)",
  "UDE0F96": "Piracicabana Breda (Santos)",
  "UDQ8D01": "Tel Turismo",
  "UDS4B48": "Tamboré",
  "UDX3G17": "Amanhecer",
  "UEA1D76": "Venetur",
  "UEB3J70": "Piracicabana Breda (Santos)",
  "UEB8I38": "Qualitat",
  "UEF0I44": "Tel Turismo",
  "UEH5I44": "Piccolotur Taipas",
  "UEM4B87": "Piracicabana Breda (Santos)",
  "UEQ8J73": "Piracicabana Breda (Santos)",
  "UEV9C97": "Transmimo Jundiai",
  "UEW0E14": "Tel Turismo",
  "UEX0I58": "Transmimo Jundiai",
  "UEY6F46": "Tel Turismo",
  "UFB6E57": "Tamboré",
  "UFF2B08": "Master Bus",
  "UFF8J40": "Piracicabana Breda (Santos)",
  "UFG8C16": "Piracicabana Breda (Santos)",
  "UFJ2J40": "Transmimo Jundiai",
  "UFP4I11": "Amanhecer",
  "UFQ0G00": "Gatti",
  "UFR3A85": "Piracicabana Breda (Santos)",
  "UFX9H68": "Piracicabana Breda (Santos)",
  "UGA1F31": "Piccolotur Taipas",
  "UGB0D34": "Exclusiva Turismo Caieiras e Jundiai",
  "UGB2F14": "Exclusiva Turismo Caieiras e Jundiai",
  "UGC7A28": "Exclusiva Turismo Caieiras e Jundiai",
  "UGD2C19": "Gatti",
  "UGD4C86": "Exclusiva Turismo Caieiras e Jundiai",
  "UGD5198": "Exclusiva Turismo Caieiras e Jundiai",
  "UGD5E94": "Piracicabana Breda (Santos)",
  "UGD6D65": "Qualitat",
  "UGF9G30": "Exclusiva Turismo Caieiras e Jundiai",
  "UGG4H57": "AS Service",
  "UGH3C89": "Exclusiva Turismo Caieiras e Jundiai",
  "UGI8J35": "Exclusiva Turismo Caieiras e Jundiai",
  "UGN3D47": "Tel Turismo",
  "UGN3G35": "Exclusiva Turismo Caieiras e Jundiai",
  "UGN8J35": "Exclusiva Turismo Caieiras e Jundiai",
  "UGO0C30": "Ribeiro Tur",
  "UGO0I20": "Transmimo Jundiai",
  "UGO3B12": "Exclusiva Turismo Caieiras e Jundiai",
  "UGO5F73": "Exclusiva Turismo Caieiras e Jundiai",
  "UGP0H98": "Exclusiva Turismo Caieiras e Jundiai",
  "UGP9E73": "Exclusiva Turismo Caieiras e Jundiai",
  "UGR5F51": "Exclusiva Turismo Caieiras e Jundiai",
  "UGR7C42": "Exclusiva Turismo Caieiras e Jundiai",
  "UGR8D64": "Tel Turismo",
  "UGT2F14": "Exclusiva Turismo Caieiras e Jundiai",
  "UGU7J38": "Exclusiva Turismo Caieiras e Jundiai",
};

export function normalizePlate(plate: unknown): string {
  if (!plate) return "N/A";
  return String(plate).replace(/[\s\-\.]/g, "").toUpperCase().trim();
}

export function extractHourFromDate(dateString: string): number {
  if (!dateString) return 0;
  const match = dateString.match(/T(\d{2}):/);
  return match ? parseInt(match[1]) : 0;
}

export function getDefaultDateRange(): { start: string; end: string } {
  const end = new Date();
  const start = new Date();
  start.setDate(start.getDate() - 30);
  return {
    start: start.toISOString().split("T")[0],
    end: end.toISOString().split("T")[0],
  };
}

export function formatDate(dateStr: string): string {
  const parts = dateStr.split("-");
  if (parts.length !== 3) return dateStr;
  const d = new Date(parseInt(parts[0]), parseInt(parts[1]) - 1, parseInt(parts[2]));
  const days = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"];
  return `${days[d.getDay()]}, ${parts[2]}/${parts[1]}/${parts[0]}`;
}

export function formatNumber(n: number): string {
  return n.toLocaleString("pt-BR");
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function normalizePoint(p: any): HeatPoint {
  const rawPlate = p.veiculo || p.vehicle_id || p.Placa || p.placa || p.vehicle || "";
  const plate = normalizePlate(rawPlate);
  const rawDate = p.data || p.Data || p.date || "";
  const cleanDate = rawDate.split("T")[0];
  let hour = 0;
  if (p.hora !== undefined && p.hora !== null) {
    hour = parseInt(String(p.hora).slice(0, 2));
  } else {
    hour = extractHourFromDate(rawDate);
  }
  // Fretadão usa campo "unidade" para identificar a empresa
  const rawUnidade = p.unidade || p.grupo || "";
  const area = rawUnidade
    ? rawUnidade.replace(/\s*[-–]\s*RASTREAMENTO FRETAD[ÃA]O.*/i, "").replace(/\s*\(RASTREAMENTO\)/i, "").trim()
    : (PLATE_TO_AREA[plate] || "Sem area");
  const km = p.km_rodado_mes ? parseFloat(p.km_rodado_mes) : undefined;
  return {
    lat: (p.latitude || p.Latitude || p.lat || 0) as number,
    lon: (p.longitude || p.Longitude || p.lng || 0) as number,
    vei: plate || "N/A",
    date: cleanDate,
    hour,
    vel: (p.velocidade || p.Velocidade || p.speed || 0) as number,
    area,
    km,
  };
}